language: python
python:
  - "3.6"
sudo: required
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - gfortran-7

before_install:
  - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-7 /usr/bin/gcc
  - sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-7 /usr/bin/g++
  - sudo ln -s /usr/bin/gfortran-7 /usr/bin/gfortran
  - gfortran --version
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda init bash
  - hash -r
  - export QT_QPA_PLATFORM='offscreen'
  - conda env create -f utils/environment_minimal.yml
  - source activate sharpy_minimal
  - conda install coverage

install:
  - git submodule init
  - git submodule update
  - git fetch -t
  - source bin/sharpy_vars.sh
  - mkdir build && cd build
  - cmake .. && make install -j 4 && cd ..
  - git submodule

script:
  - coverage run -m unittest discover

after_success:
  - bash <(curl -s https://codecov.io/bash)
