name: sharpy_env
channels:
  - defaults
dependencies:
  - blas=1.0=mkl
  - ca-certificates=2019.11.27=0
  - certifi=2019.11.28=py37_0
  - colorama=0.4.1=py37_0
  - configobj=5.0.6=py37_1
  - coverage=4.5.4=py37h1de35cc_0
  - dill=0.3.1.1=py37_0
  - eigen=3.3.7=h04f5b5a_0
  - icu=58.2=h4b95b61_1
  - intel-openmp=2019.4=233
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.2.1=h475c297_4
  - libgfortran=3.0.1=h93005f0_2
  - libiconv=1.15=hdd342a3_7
  - libxml2=2.9.9=hf6e021a_1
  - libxslt=1.1.33=h33a18ac_0
  - lxml=4.4.2=py37hef8c89e_0
  - mkl=2019.4=233
  - mkl-include=2019.4=233
  - mkl-service=2.3.0=py37hfbe908c_0
  - mkl_fft=1.0.15=py37h5e564d8_0
  - mkl_random=1.1.0=py37ha771720_0
  - ncurses=6.1=h0a44026_1
  - numpy=1.17.4=py37h890c691_0
  - numpy-base=1.17.4=py37h6575580_0
  - openssl=1.1.1d=h1de35cc_3
  - pandas=0.25.3=py37h0a44026_0
  - pip=19.3.1=py37_0
  - python=3.7.5=h359304d_0
  - python-dateutil=2.8.1=py_0
  - pytz=2019.3=py_0
  - readline=7.0=h1de35cc_5
  - scipy=1.3.1=py37h1410ff5_0
  - setuptools=42.0.2=py37_0
  - six=1.13.0=py37_0
  - sqlite=3.30.1=ha441bb4_0
  - tk=8.6.8=ha441bb4_0
  - wheel=0.33.6=py37_0
  - xz=5.2.4=h1de35cc_4
  - zlib=1.2.11=h1de35cc_3
  - pip:
    - apptools==4.5.0
    - envisage==4.9.0
    - mayavi==4.7.1
    - pyface==6.1.2
    - pygments==2.5.2
    - traits==5.2.0
    - traitsui==6.1.3
    - vtk==8.1.2

